language: go
sudo: false
go:
- tip
before_install:
- openssl aes-256-cbc -K $encrypted_16e2409ca575_key -iv $encrypted_16e2409ca575_iv
  -in key.json.enc -out key.json -d
- go get -t -v ./...
script:
- ./test.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: gae
  keyfile: key.json
  project: go-swagg
  config: cmd/app.yaml
